services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

volumes:
  pgdata:
